label: Values
icon: verified
picker_preview:
  text:
    - Values
  icon:
    - verified
preview:
  text:
    - key: title
    - Values
  icon:
    - verified
value:
  _type: values
  title:
  subtitle:
  tagline:
  items: []
  columns: 2
_inputs:
  subtitle:
    type: textarea
  items:
    type: array
    options:
      structures: _structures.items
