import { registerAstroComponent } from '@cloudcannon/editable-regions/astro';

import Hero from '~/components/widgets/Hero.astro';
import Hero2 from '~/components/widgets/Hero2.astro';
import HeroText from '~/components/widgets/HeroText.astro';
import Note from '~/components/widgets/Note.astro';
import Features from '~/components/widgets/Features.astro';
import Features2 from '~/components/widgets/Features2.astro';
import Features3 from '~/components/widgets/Features3.astro';
import ContentWidget from '~/components/widgets/Content.astro';
import Steps from '~/components/widgets/Steps.astro';
import Steps2 from '~/components/widgets/Steps2.astro';
import FAQs from '~/components/widgets/FAQs.astro';
import Stats from '~/components/widgets/Stats.astro';
import CallToAction from '~/components/widgets/CallToAction.astro';
import Testimonials from '~/components/widgets/Testimonials.astro';
import Pricing from '~/components/widgets/Pricing.astro';
import BlogLatestPosts from '~/components/widgets/BlogLatestPosts.astro';
import BlogHighlightedPosts from '~/components/widgets/BlogHighlightedPosts.astro';
import Brands from '~/components/widgets/Brands.astro';
import Contact from '~/components/widgets/Contact.astro';

registerAstroComponent('hero', Hero);
registerAstroComponent('hero2', Hero2);
registerAstroComponent('hero_text', HeroText);
registerAstroComponent('note', Note);
registerAstroComponent('features', Features);
registerAstroComponent('features2', Features2);
registerAstroComponent('features3', Features3);
registerAstroComponent('content', ContentWidget);
registerAstroComponent('steps', Steps);
registerAstroComponent('steps2', Steps2);
registerAstroComponent('faqs', FAQs);
registerAstroComponent('stats', Stats);
registerAstroComponent('call_to_action', CallToAction);
registerAstroComponent('testimonials', Testimonials);
registerAstroComponent('pricing', Pricing);
registerAstroComponent('blog_latest_posts', BlogLatestPosts);
registerAstroComponent('blog_highlighted_posts', BlogHighlightedPosts);
registerAstroComponent('brands', Brands);
registerAstroComponent('contact', Contact);
